#if !canImport(ObjectiveC)
import XCTest

extension PosteTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__PosteTests = [
        ("testCancelled", testCancelled),
        ("testDone", testDone),
        ("testOptional", testOptional),
        ("testRequired", testRequired),
        ("testRequiredAsync", testRequiredAsync),
        ("testVoid", testVoid),
    ]
}

public func __allTests() -> [XCTestCaseEntry] {
    return [
        testCase(PosteTests.__allTests__PosteTests),
    ]
}
#endif
